### PR TITLE
microsoft_translator added

### PR DESCRIPTION
**Pull request by KirillSklyarenko**
new file: microsoft.py;
updated files:
    exceptions.py (added MicrosoftAPIException to show error messages returned by the API)
    constants.py (added the request to Microsoft api link for supported languages; I believed it is better to request the up-to-date list of languages than to hardcode the current one; however, that list will not change often; it's a bit controversial).

### CODE REVIEW

**Comment by nidhaloff** [comment]
I just fixed a small typo in constants.py, otherwise, everything looks good. Thank you

**Comment by nidhaloff** [comment]
@KirillSklyarenko  thanks for your contribution to the project. Would you mind working further on the Microsoft translator if we face any bugs in the future?

**Comment by KirillSklyarenko** [comment]
@nidhaloff, yes sure I'll do my best. Actually for now I should be doing two things: new text to the docs and adding MicrosoftTranslator to the init file.

**Comment by nidhaloff** [comment]
@KirillSklyarenko  I already did that thanks ;) I also added a credits section in the Readme and posted your name there. Feel free to update anything in the readme, It would be helpful to add an example there about using the Microsoft translator

**Comment by KirillSklyarenko** [comment]
@nidhaloff, ok I see. I'll try to extend the Readme, but first I'll have to read a bit about that (it will be my first try on that task, like everything else).

**Pull request merged**
