### PR TITLE
Excel column data translation feature added

### PR DESCRIPTION
**Pull request by debjyoti003**
I have added the excel column data translation feature as requested by foubou. Please merge this if you find it suitable, also if you want to add something more, you can tell me.

### CODE REVIEW

**Review by nothead31 — CHANGES_REQUESTED** [review]
1. Instead of putting it in google_trans.py, could you put it in __main__.py and set it up so that either:

    A. The command line argument TEXT accepts spreadsheets as well as plaintext and the module automatically redirects to either text translation or spreadsheet translation.

    B. Add a sub-command for spreadsheet translation so the user can choose whether to translate text or spreadsheets.

    C. Add a new entry point (for example, "dt-excel") and separate command line tree to achieve the above.

2. Secondly, and optionally (meaning this isn't required, but would be nice), verify that the pandas dataframe can accept various spreadsheet filetypes including GDrive Sheets, LibreOffice, and various Excel formats.

3. Finally, and again optionally, implement pytest functionality to test the output. Ideally, we would have the sample data I requested from foubou to use as the testing basis, but whoever implements the tests can also create a sample.

I'll add these three things to a milestone, so at least add the first requested feature and the rest can come later.

**Comment by debjyoti003** [comment]
@nothead31 can you please elaborate the points B and C, sub-command in the sense, using @click decorator for that to achieve?

**Comment by nothead31** [comment]
Yes, exactly. I was just brainstorming a few different ways to accomplish the goal, but whatever you find works best will do.

**Comment by debjyoti003** [comment]
@nothead31 , I'll have to study a little bit about @click, then i will add it pretty soon.

**Comment by nidhaloff** [comment]
@nothead31 @debjyoti003 Notice that this will introduce a new dependency, which is pandas. We don't want to introduce a new "heavy" dependency just for a rare use case like this one. For this to work fine and for the PR to be accepted, we need to register pandas as a "secondary" dependency. 
I'm not sure how to do it in setup.py but I remember that it can be done. That way, users can choose to additionally install pandas if they want the new excel translation functionality, otherwise, pandas will not be installed by default if you install deep-translator. **This is very important!**

**Comment by debjyoti003** [comment]
Sure @nidhaloff, also what I noticed is as we are using read_excel from pandas which also asks for xlrd or openpyxl, which are also the dependencies, so if we add it, then those two also need to be added as the dependencies.

**Comment by nothead31** [comment]
Not necessarily. Pandas will handle its own dependencies so we don't need to specify them as dependencies in the setup scripts, although that doesn't change @nidhaloff's goal to ensure pandas remains a non-required dependency for our project. Also, when documenting this new feature, mentioning those sub-dependencies would be beneficial for documentation purposes.

**Comment by nothead31** [comment]
@debjyoti003 were you able to make the changes to main.py? I am in the middle of converting the project to use poetry instead of setuptools, which will alleviate @nidhaloff's suggestion to set pandas as an optional dependency, so all we need is the CLI support put in place.

**Comment by debjyoti003** [comment]
No @nothead31, I got busy in my work, but no worries, by tomorrow I will make the changes

**Comment by nothead31** [comment]
No rush, i was just wondering how it was going.

**Pull request closed without merging**
