### PR TITLE
Added functionality for -lang/--languages flag to the CLI usage to return the languages supported by the chosen translator service.

### PR DESCRIPTION
**Pull request by bigsbunny**
Hey @nidhaloff. I have added a bit of a functionality to the cli.py file that adds support for a -lang/--languages flag that takes in the -trans flag with the argument and returns the languages supported by the chosen translator service, in the form of a dictionary with language along with its abbreviation. I have updated the README as well to incorporate this functionality as documentation.

Please go through it once and do let me know if any further changes/optimizations could be made. I am actually new to open source contributions and it would be of great help if you could guide me if everything I have done up to this point is in line with the general workflow and guidelines of contributing.

### CODE REVIEW

**Comment by nidhaloff** [comment]
thanks for your contribution. Feel free to improve anything. There are some translators which can't (yet) be used from the CLI. You can work on that further if you like ;)

**Comment by bigsbunny** [comment]
Hey @nidhaloff. Thank you for your review. I will surely try working on that. Just wanted to ask if everything related to this PR was in line with the guidelines or is there something I should keep in mind for future PRs? It would be of great help if you could help me with this.

**Comment by nidhaloff** [comment]
@bigsbunny Thanks ;) you ve done a good job. The important thing is to keep contributing (generally and not only to this project) in order to keep improving yourself. I assume you tested the functionality before submiting the PR. 

Normally, I would expect some basic tests to be added from contributors, but in your case, your PR is not that advanced and that's why I don't see that it's necessary to add some tests for it. However, if you want to work on something more advanced (let's say for example you want to improve a translator or add a new one), in this case it would be great if you add some tests to make sure that nothing was broken. In this case, writing comments is also very important.

As I said, I think you ve done a good job and I congratulate you (if this was your first contribution to open source). You can build up, try new/advanced things and always try to improve yourself through improving other people's code (like you did here). Feel free to contact me if you have any new ideas about the project or just make a PR and I would happily review it. 

Best Regards

**Comment by bigsbunny** [comment]
@nidhaloff thank you so much for the motivation, will surely keep contributing to open source projects! Yeah, I tested the functionality from the terminal thoroughly before submitting this PR. 

Yeah, I thought as the CLI usage basically involves the calling of respective translate method (of python) for the translator chosen after passing the parsed arguments received from the terminal, tests weren't needed to test the usage from the terminal. 

Thank you again! This was my very first open-source contribution and I am glad to be of help to this tool that seemed really interesting to me. I'll try my best to improve upon it even more and better myself through doing that.

Regards.

**Pull request merged**
