### PR TITLE
Asked changes done for excel

### PR DESCRIPTION
**Pull request by debjyoti003**
@nothead31 please have a look at it, if anything is missing please tell me. As per your requirement I have set it up in main.py instead of google_trans.py.

### CODE REVIEW

**Comment by nothead31** [comment]
The translate function won't call properly without the right inputs, you'll need to add a few more things to the command:
- translator and api options similar to the default translate command
- convert each line needing translation to a string, then passing it and the translator/api selections over to the translate function (along with any necessary formatting)
- read back those lines into the dataframe (essentially a minor change to what you already have)

I'll go ahead and reject the previous pull request to avoid duplicates, don't worry about seeing the rejection notice. You should be able to add your changes to this request without creating a new one.

**Comment by nidhaloff** [comment]
@debjyoti003 @nothead31 We need to check how would this behave in case the user did not install pandas? what would happen? Even if pandas is marked as an optional dependency in poetry. I'm not sure if the code won't break since the interpreter will try to run the code from top to bottom, so if it hits the line `import pandas as pd` and I did not install pandas. What will happen in this case? 
did you guys check this?

**Comment by debjyoti003** [comment]
@nidhaloff haven't checked, need to check it.

**Comment by debjyoti003** [comment]
@nothead31 please have a look at the changes done which you have asked for.

**Comment by nothead31** [comment]
@nidhaloff I know poetry provides support for optional dependencies, but I have to figure out what exactly happens when it runs into this situation. I've been delayed at working this week because of medical issues, but hopefully next week I'll be back to normal.

**Comment by nothead31** [comment]
Hi, @nidhaloff, I found a couple of documentation pages regarding optional dependencies. [This page from setuptools docs](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html?highlight=extras_require#optional-dependencies) gives guidance on how to handle optional dependencies in the code, and [this section of Poetry docs](https://python-poetry.org/docs/pyproject/#extras) explains additional steps to enable optional dependencies. Basically, the key takeaways are:

- In addition to the dependency being declared with the `optional=True` tag under [tool.poetry.dependencies], it also needs to be added under a new tag underneath [tool.poetry.extras]
- That tag needs to be added to a new entry point, for example
```
[tool.poetry.scripts]
deep-translator-excel = 'deep-translator.main:excel [extras-tag-name]`
```
or similar. Poetry doesn't explicitly clarify how to set an optional dependency for the end-user like setuptools does, so it might take some experimenting to get the syntax right.

@debjyoti003, these references might be useful for you as well, I'm still researching the topic though, since its even more scarcely documented than some other issues we've been working on.

**Comment by nidhaloff** [comment]
@nothead31 Thank you. Hmm, I'm still wondering how can this possibly works. Don't we need to move the `import pandas as pd `inside the `excel_translation` function?

Because, I mean if I don't have pandas installed and want to access a function or any piece of code inside main.py, then my program would crash in the import pandas as pd line since I don't have it. 

I imagine a solution for this can be to move the import statement inside the function. That way, the line `import pandas` will only be executed by the interpreter when that excel_translation function is called, otherwise never. 

Another solution, I can think of is to wrap the import pandas as pd statement using a try-catch block. Something like this:

```
try:
      import pandas as pd
except:
      pass
```

These are my suggestions for a fix because as I said, I can't see how this would work even when specifying this as an optional dep in poetry or setuptools. Basically, from my understanding, poetry just provides a way to install packages as extra dependencies. However, in our codebase, we need to deal with this alone and from my understanding, python would always throw an exception if it can't import pandas and hence this will be a bug for users that will not install pandas.

**Comment by nothead31** [comment]
That's where the documentation falls short. Optional dependencies are not a Poetry feature, they're present in setuptools and distutils, but none of the documentation covers actually applying it. I think the best bet would be to head to stackoverflow or get with the guys at setuptools to see how they implemented the feature.

**Comment by nidhaloff** [comment]
I'm closing this since there have been no updates about it

**Pull request closed without merging**
