### PR TITLE
Merge fix

### PR DESCRIPTION
**Pull request by nothead31**
Fixed the merge conflicts with documentation changes. Removing that branch and PR to keep things organized.

### CODE REVIEW

**Comment by nothead31** [comment]
Build failures are due to moving README.rst from the root folder to /docs, a quick fix to the build script should resolve. As I mentioned, GitHub does understand how to read the README.rst from inside the /docs folder, as demonstrated [in my own project](https://github.com/nothead31/api-keychain) (ignore the issues with the documentation itself)

**Comment by nidhaloff** [comment]
@nothead31 Thanks for working on this. 

It is so weird that the build is failing! At the moment, the build will just install dependencies and run tests. That has nothing to do with the README. I will merge your PR anyway and I will check why this is happening asap

**Comment by nidhaloff** [comment]
@nothead31 aah I assume because of this line in pyproject.toml: `readme = "README.rst"` 

poetry would search for a README.rst but its not clever enough like github to search the whole project tree structure. I will check how to fix this

**Comment by nothead31** [comment]
It might be as simple as `readme = './docs/readme.rst'`. I've been trying to get another project back on its feet, or i'd investigate, but its not like its the biggest problem we have.

**Comment by nidhaloff** [comment]
@nothead31 Already solved. `readme = 'docs/readme.rst'` solved the issue

**Pull request merged**
